ClothesShopApp/Areas/Admin/Controllers/ProductController.cs
using ClothesShopApp.Business;
using ClothesShopApp.Data.Entity;
using ClothesShopApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualBasic;

namespace ClothesShopApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly ProductService _productService;
        private readonly CategoryService _categoryService;
        private readonly ProductImageSerivce _productImageSerivce;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ProductVariantService _productVariantService;
        private readonly VariantService _variantService;
        private readonly VariantValueService _variantValueService;
        public ProductController(
            ProductService productService,
            CategoryService categoryService,
            ProductImageSerivce productImageSerivce,
            IWebHostEnvironment webHostEnvironment,
            ProductVariantService productVariantService,
            VariantService variantService,
            VariantValueService variantValueService)
        {
            _productService = productService;
            _categoryService = categoryService;
            _productImageSerivce = productImageSerivce;
            _webHostEnvironment = webHostEnvironment;
            _productVariantService = productVariantService;
            _variantService = variantService;
            _variantValueService = variantValueService;

        }
        public IActionResult Index()
        {

            var model = _productService.ProductMapToViewModel(null);


            return View(model);
        }



        [HttpGet]
        public IActionResult CreateProduct()
        {
            var viewModel = _productService.GetCategories();


            return View(viewModel);
        }

        [HttpPost]
        public IActionResult CreateProduct(ProductViewModel model, IEnumerable<IFormFile> pictureFiles)
        {



            if (ModelState != null)
            {


                int? parentId = null;


                parentId = _productService.GetSelectedParentId(model);
                var newProduct = _productService.GetNewProduct(model, parentId);
                _productService.CreateProduct(newProduct);

                foreach (var pictureFile in pictureFiles)
                {
                    string uniqueFileName = Guid.NewGuid().ToString() + "_" + pictureFile.FileName;
                    string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");

                    string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        pictureFile.CopyTo(fileStream);
                    }

                    // Yeni resim nesnesi oluşturma ve ürüne ekleme
                    var productImage = new ProductImage
                    {
                        url = uniqueFileName,
                        ProductId = newProduct.productId
                    };

                    _productImageSerivce.CreateImageProduct(productImage);
                }

                return RedirectToAction("AddVariantsToProduct", new { productId = newProduct.productId });


            }
            return View(model);
        }
        
        [HttpPost]
        public IActionResult DeleteProduct(int id)
        {
            _productService.DeleteProduct(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditProduct(int id)
        {

            var model = _productService.GetSelectedProduct(id);


            return View(model);
        }
        [HttpPost]
        public IActionResult EditProduct(ProductViewModel model, List<IFormFile> NewImages, List<int> DeletedImages, List<IFormFile> UpdatedImages)
        {
            if (DeletedImages != null && DeletedImages.Count > 0)
            {
                foreach (var imageId in DeletedImages)
                {
                    var image = _productImageSerivce.GetAllProductImages().Where(c => c.productImageId == imageId).FirstOrDefault();
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", image.url);
                    if (System.IO.File.Exists(imagePath))
                    {
                        System.IO.File.Delete(imagePath);
                    }

                    // Veritabanından da silme işlemi
                    _productImageSerivce.DeleteImageProduct(imageId);
                }
            }
            if (UpdatedImages != null && UpdatedImages.Count > 0)
            {
                for (int i = 0; i < UpdatedImages.Count; i++)
                {
                    if (UpdatedImages[i] != null)
                    {
                        var imageId = model.PictureIds[i]; // ID ile eşleştirme
                        var image = _productImageSerivce.GetAllProductImages()
                            .FirstOrDefault(c => c.productImageId == imageId);

                        if (image != null)
                        {
                            var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", image.url);

                            // Eski görseli sil
                            if (System.IO.File.Exists(oldImagePath))
                            {
                                System.IO.File.Delete(oldImagePath);
                            }

                            // Yeni görseli yükle
                            var newImageName = $"{Guid.NewGuid()}_{UpdatedImages[i].FileName}";
                            var newImagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", newImageName);

                            using (var stream = new FileStream(newImagePath, FileMode.Create))
                            {
                                UpdatedImages[i].CopyTo(stream);
                            }
                            image.url = newImageName;
                            image.ProductId = model.ProductId;

                            // Veritabanında da güncelleme işlemi
                            _productImageSerivce.UpdateImageProduct(image);
                        }
                    }
                }
            }
            if (NewImages != null && NewImages.Count > 0)
            {
                foreach (var newImage in NewImages)
                {
                    var newImageName = $"{Guid.NewGuid()}_{newImage.FileName}";
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", newImageName);

                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        newImage.CopyTo(stream);
                    }
                    var image = new ProductImage
                    {
                        url = newImageName,
                        ProductId = model.ProductId,
                    };
                    // Yeni görseli veritabanına ekle
                    _productImageSerivce.CreateImageProduct(image);
                }
            }
            if (ModelState != null)
            {

                var updatedProduct = _productService.GetUpdatedProduct(model);
                _productService.UpdateProduct(updatedProduct);
                return RedirectToAction("Index");

            }
            model.Categories = _productService.GetSelectListCategory();
            return View(model);
        }

        [HttpGet]
        public IActionResult LoadSubCategories(int parentId)
        {
            var subCategories = _productService.GetCategorySelectList(parentId);


            return Json(subCategories);
        }
        [HttpGet]
        public IActionResult AddVariantsToProduct(int productId)
        {
            var productVariants = _productVariantService.GetAllProductVariants().Where(p => p.ProductId == productId).ToList();
            var variantDetails = (from pv in productVariants
                                  join vv in _variantValueService.GetAllVariantValues() on pv.VariantValueId equals vv.VariantValueId
                                  join vt in _variantService.GetAllVariants() on vv.VariantId equals vt.VariantId
                                  select new
                                  {
                                      VariantTypeName = vt.Name,
                                      VariantValueName = vv.Value,
                                      Stock = pv.Stock,
                                      ProductVariantId = pv.ProductVariantId
                                  }).ToList();

            var variantTypeGroups = variantDetails
             .GroupBy(v => v.VariantTypeName)
             .Select(group => new VariantTypeViewModel
             {
                 VariantTypeName = group.Key,
                 Values = group.Select(v => v.VariantValueName).ToList(),
                 Stock = group.Select(s => s.Stock).ToList(),
                 ProductVariantId = group.Select(p=> p.ProductVariantId).ToList()
             })
             .ToList();

            //var newModel = new ProductVariantsViewModel
            //{
            //    ProductId = productId,
            //    VariantTypes = variantTypeGroups
            //};
            
            var variatns = _variantService.GetAllVariants().ToList();
            var variantValues = _variantValueService.GetAllVariantValues().ToList();
            var model = new VariantViewModel
            {
                ProductId = productId,
                Variants = variatns,
                VariantValues = variantValues,
                VariantTypes = variantTypeGroups
            };
            return View(model);
        }

        [HttpPost]

ClothesShopApp/Areas/Admin/Controllers/VariantController.cs
using ClothesShopApp.Business;
using ClothesShopApp.Data.Entity;
using ClothesShopApp.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace ClothesShopApp.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class VariantController : Controller
    {
        private readonly VariantService _variantService;
        private readonly VariantValueService _variantValueService;
        public VariantController(VariantService variantService, VariantValueService variantValueService)
        {
            _variantService = variantService;
            _variantValueService = variantValueService;
        }
        public IActionResult Index()
        {
            var variants = _variantService.GetAllVariants().ToList();
            var model = _variantService.ConvertToModel(variants);
            return View(model);
        }
        [HttpGet]
        public IActionResult CreateVariant(int? variantId)
        {
            if (variantId == null)
            {
                var model = new VariantViewModel();
                model.VariantValues = null;
                return View(model);
            }
            else
            {
                var model = new VariantViewModel();
                model.Id = variantId.Value;
                var variantValues = _variantValueService.GetAllVariantValues().Where(x => x.VariantId == variantId).ToList();
                model.VariantValues = variantValues;
                return View(model);
            }

        }

        [HttpPost]
        public JsonResult CreateVariant(VariantViewModel model)
        {
            if (model.Id == 0)
            {
                var variant = _variantService.ConvertToVariant(model);
                _variantService.CreateVariant(variant);
               
                model.Id = variant.VariantId;
            }
            else
            {
                var variantValue = _variantValueService.ConvertToVariantValue(model);
                _variantValueService.CreateVariantValue(variantValue);
            }


            var variantValues = _variantValueService.GetAllVariantValues().Where(x => x.VariantId == model.Id).ToList();

            var result = new
            {
                variantId = model.Id,
                variantValues = variantValues.Select(v => new
                {
                    variantValueId = v.VariantValueId,
                    variantId = v.VariantId,
                    value = v.Value
                }).ToList()
            };
            
            return Json(result);
        }

        public IActionResult EditVariant(int id)
        {
			var variant = _variantService.GetAllVariants()
										   .Where(c => c.VariantId == id)
										   .Select(c => new Variant
										   {
											  VariantId = c.VariantId,
                                              
                                              Name = c.Name

										   })
										   .FirstOrDefault();

			if (variant == null)
			{
				return NotFound();
			}
			return View(variant); 
        }
		[HttpPost]
		public IActionResult EditVariant(Variant variant)
		{
			

			if (ModelState.IsValid)
			{
				var editedCategory = new Variant
				{
					VariantId=variant.VariantId,
                    Name = variant.Name

				};
				TempData["SuccessMessage"] = "Varaynt başarıyla güncellendi.";
				_variantService.UpdateVariant(editedCategory);
				return RedirectToAction("Index");
			}
			return View(variant);


		}


		public IActionResult DeleteVariant(int id)
        {
            _variantService.DeleteVariant(id);
            return RedirectToAction("Index");
        }
        public void DeleteVariantValue(int valueId)
        {
            _variantValueService.DeleteVariantValue(valueId);


        }



    }
}

ClothesShopApp/Views/Shared/_AdminLayout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}




<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Modernize Free</title>
    <link rel="shortcut icon" type="image/png" href="../assets-login/images/logos/favicon2.png" />
    <link rel="stylesheet" href="../assets-login/css/styles.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.11.3/font/bootstrap-icons.min.css" integrity="sha512-dPXYcDub/aeb08c63jRq/k6GaKccl256JQy/AnOq7CAnEZ9FzSL9wSbcZkMp4R26vBsMLFYH4kQ67/bbV8XaCQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
    <header class="app-header">
        <nav class="navbar navbar-expand-lg navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item d-block d-xl-none">
                    <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
                        <i class="ti ti-menu-2"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link nav-icon-hover" href="javascript:void(0)">
                        <i class="ti ti-bell-ringing"></i>
                        <div class="notification bg-primary rounded-circle"></div>
                    </a>
                </li>
            </ul>
            <div class="navbar-collapse justify-content-end px-0" id="navbarNav">
                <ul class="navbar-nav flex-row ms-auto align-items-center justify-content-end">
                   
                    <li class="nav-item dropdown">
                       
                        <div class="dropdown-menu dropdown-menu-end dropdown-menu-animate-up" aria-labelledby="drop2">
                            <div class="message-body">
                                <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                    <i class="ti ti-user fs-6"></i>
                                    <p class="mb-0 fs-3">My Profile</p>
                                </a>
                                <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                    <i class="ti ti-mail fs-6"></i>
                                    <p class="mb-0 fs-3">My Account</p>
                                </a>
                                <a href="javascript:void(0)" class="d-flex align-items-center gap-2 dropdown-item">
                                    <i class="ti ti-list-check fs-6"></i>
                                    <p class="mb-0 fs-3">My Task</p>
                                </a>
                                <a href="./authentication-login.html" class="btn btn-outline-primary mx-3 mt-2 d-block">Logout</a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    
    
        <!--  Body Wrapper -->
        <div class="page-wrapper" id="main-wrapper" data-layout="vertical" data-navbarbg="skin6" data-sidebartype="full" data-sidebar-position="fixed" data-header-position="fixed">
            <!-- Sidebar Start -->
            <aside class="left-sidebar">
                <!-- Sidebar scroll-->
                <div>
                    <div class="brand-logo d-flex align-items-center justify-content-between">
                        <a href="" class="text-nowrap logo-img">
                            @* <img src="../assets-login/images/favicon.png" width="180" alt="" /> *@
                        </a>
                        <div class="close-btn d-xl-none d-block sidebartoggler cursor-pointer" id="sidebarCollapse">
                            <i class="ti ti-x fs-8"></i>
                        </div>
                    </div>
                    <!-- Sidebar navigation-->
                    <nav class="sidebar-nav scroll-sidebar" data-simplebar="">
                        <ul id="sidebarnav">

                            <li class="nav-small-cap mb-2">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Kategori işelmleri</span>
                            </li>

                           


                                <li class="sidebar-item mb-3">
                                    <a class="sidebar-link" asp-action="Index" asp-controller="Category" aria-expanded="false">
                                        <span>
                                            <i class="ti ti-cards"></i>
                                        </span>

                                        <span class="hide-menu">Kategoriler</span>
                                    </a>
                                </li>
                        <li class="sidebar-item mb-3">
                            <a class="sidebar-link" asp-action="CreateCategory" asp-controller="Category" aria-expanded="false">
                                <span>
                                    <i class="ti ti-cards"></i>
                                </span>

                                <span class="hide-menu">Kategori Ekle</span>
                            </a>
                        </li>
                        


                        <li class="nav-small-cap mb-2">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Ürün işelmleri</span>
                        </li>

                        <li class="sidebar-item mb-3">
                            <a class="sidebar-link" asp-action="Index" asp-controller="Product" aria-expanded="false">
                                <span>
                                    <i class="ti ti-cards"></i>
                                </span>

                                <span class="hide-menu">Ürünler</span>
                            </a>
                        </li>

                        <li class="sidebar-item mb-3">
                            <a class="sidebar-link" asp-action="CreateProduct" asp-controller="Product" aria-expanded="false">
                                <span>
                                    <i class="ti ti-cards"></i>
                                </span>

                                <span class="hide-menu">Ürün Ekle</span>
                            </a>
                        </li>

                        <li class="nav-small-cap mb-2">
                            <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                            <span class="hide-menu">Varyant işelmleri</span>
                        </li>

                        <li class="sidebar-item mb-3">
                            <a class="sidebar-link" asp-action="Index" asp-controller="Variant" aria-expanded="false">
                                <span>
                                    <i class="ti ti-cards"></i>
                                </span>

                                <span class="hide-menu">Varyantlar</span>
                            </a>
                        </li>
                            
                            <li class="nav-small-cap">
                                <i class="ti ti-dots nav-small-cap-icon fs-4"></i>
                                <span class="hide-menu">Hesap</span>
                            </li>

                          

                            <li class="sidebar-item">
                                <a class="sidebar-link" asp-action="Login" asp-controller="" aria-expanded="false">
                                    <span>
                                        <i class="ti ti-logout"></i>
                                    </span>
                                    <span class="hide-menu">Çıkış yap</span>
                                </a>
                            </li>


                        </ul>

                    </nav>
                    <!-- End Sidebar navigation -->
                </div>
                <!-- End Sidebar scroll-->
            </aside>
            <!--  Sidebar End -->
            <!--  Main wrapper -->
            <div class="body-wrapper">
                <!--  Header Start -->
                @*
            <header class="app-header">
            <nav class="navbar navbar-expand-lg navbar-light">
            <ul class="navbar-nav">
            <li class="nav-item d-block d-xl-none">
            <a class="nav-link sidebartoggler nav-icon-hover" id="headerCollapse" href="javascript:void(0)">
            <i class="ti ti-menu-2"></i>
            </a>
            </li>

            </ul>

            </nav>
            </header>
            *@


                <!--  Header End -->
                @RenderBody()
            </div>
        </div>
    



    <script src="../assets-login/libs/jquery/dist/jquery.min.js"></script>
    <script src="../assets-login/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="../assets-login/js/app.min.js"></script>
    <script src="../assets-login/libs/apexcharts/dist/apexcharts.min.js"></script>
    <script src="../assets-login/libs/simplebar/dist/simplebar.js"></script>
    <script src="../assets-login/js/dashboard.js"></script>
    <script src="../assets-login/js/sidebarmenu.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>